name: Django CI

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Migrate
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Deploy
      run: |
        . venv/bin/activate
        python manage.py runserver 0.0.0.0:8000
